name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: visha-ui
          repo: GithubDemo2
          github_token: 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
          workflow_file_name: demo2.yml
          ref: main
          wait_interval: 2
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          
          
         
        

  


