name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="visha-ui" 
          repo_name="GithubDemo2"  
          event_type="trigger-workflow" 
          service="demo-app"
          version="v1.0.0"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/visha-ui/GithubDemo2/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
