name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          event_type="trigger-workflow" 
          service="demo-app"
          version="v1.0.0"         
         
        

  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token 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" \
            -H "X-GitHub-Api-Version: 2024-01-28" \
            https://api.github.com/repos/visha-ui/GithubDemo2/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"
