name: Send repository dispatch event

on:
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        run: |
          curl -u \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/visha-ui/GithubDemo2/dispatches \
          -d '{"event_type":"dispatch-event"}'
